### PR TITLE
Upgrade Solr, Zeppelin, bug fixes

### LINKED ISSUE #1: Remove the need to specify facet=true in the facet command
When using `facet` command, a user should not need to specify `facet=true` in a query since it is redundant.

### LINKED ISSUE #7: total document counts do not match
Hi Team

I am observing a discrepancy between the actual number of documents in a collection and the number shown in the zeppelin-notebook when performing "use <collection-name>" command.

The one on the UI after the use command is significantly lower than the actual.
Also when I run a facet or streaming expression query the doc counts are significantly higher than the total docs shown in the section created using the "use" command.

### PR DESCRIPTION
**Pull request by kiranchitturi**
* Upgrade Zeppelin to 0.8.0
* Upgrade Solr to 7.5.0
* Fixes #1, #7, #8, #9

### CODE REVIEW

**Comment by janhoy** [comment]
Glad to see some movement in this project, I wondered whether it is maintained or not :)

**Comment by epugh** [comment]
Whats the timeline for this being merged?  I suspect that the version of the zeppelin-solr demoed at Activiate was based on this new branch!  Is there a maven repo out there?

**Comment by epugh** [comment]
I found https://oss.sonatype.org/content/repositories/snapshots/com/lucidworks/zeppelin/zeppelin-solr/ has a version of the plugin, but can't figure out how to tell `./bin/install-interpreter.sh` to use this as the repository!

**Comment by epugh** [comment]
Okay, so I finally figured out that the way to go was to install the plugin was to first install if via ./bin/interpreter-install.sh -n solr -t path_to_jar

Then, I took all of the dependencies from the build, which ended up oddly not in `/target/` but in `/target/../../interpreter/solr` and moving them into the newly created `/zeppelin/interperter/solr`

**Comment by kiranchitturi** [comment]
Hi,

I just got back from the conference. Will merge this and release a version soon. 

Installing the interpreter should be as easy as 

```
./bin/install-interpreter.sh --name solr --artifact com.lucidworks.zeppelin:zeppelin-solr:0.0.1-beta2
```

**Comment by epugh** [comment]
Do I want beta2?   I thought this branch is beta3....?

**Comment by epugh** [comment]
Regardless, I'll check it out soon!  Thanks for merging.

**Comment by kiranchitturi** [comment]
@epugh I released 0.1.0 just now. Use this command to install the latest (present in the README too)

```
./bin/install-interpreter.sh --name solr --artifact com.lucidworks.zeppelin:zeppelin-solr:0.1.0
```

Just this command should be enough. No need to copy or transfer files. If there is a bug, please create an issue to report

**Pull request merged**
