### PR TITLE
update to Zeppelin 0.9.0-preview1

### PR DESCRIPTION
**Pull request by epugh**
This updates the Zeppelin dependency, and I had to bump the Scala plugin version to get it to build.

### CODE REVIEW

**Comment by epugh** [comment]
@kiranchitturi and @joel-bernstein I wanted to poke you'all on reviewing this upgrade;-).  Hope things are going well.

**Comment by epugh** [comment]
Hi @joel-bernstein...   I'm really enjoying goitng through your logs tutorial, using a real estate sample data set, and it's been super helpful.  I wanted to poke you on thoughts on upgrading to Zeppelin 0.9?

**Comment by epugh** [comment]
If anyone else wants to try out the plugin, I did confirm you can checkout the branch and then run these commands to install the snapshot version with the 0.9.0 support.

```
mvn clean install
```

Then go to your Zeppelin install and run:

```
./bin/install-interpreter.sh --name solr --artifact com.lucidworks.zeppelin:zeppelin-solr:0.1.7-SNAPSHOT
```

**Comment by epugh** [comment]
@gerlowskija since you are opening some PR's, do you mind looking at this?  I *think* it's maybe no longer needed?

**Comment by gerlowskija** [comment]
LGTM - though I might pull the Solr dep change into a separate PR/commit if I can (I see there's already one filed for that.)  Will revisit tonight or tomorrow.

We should update our internal dependencies regardless, but I'm curious - does zeppelin-solr 0.1.6 not work for you on latest Zeppelin?  We (Joel B and I) have been using the latest plugin with Zeppelin 0.9.0 since shortly after it was released.

**Comment by epugh** [comment]
Dependabot is competing with my PR ;-).    Zeppelin-solr-0.1.6 does work with my existing Solr 8.7 cluster and Zeppelin 0.9.0.

**Pull request closed without merging**
